version: '2'
services:
  nginx:
    restart: always
    build: ./survey/
    ports:
      - "8080:80"
    volumes:
      - /www/public
      - "./survey/app:/src/app"
    depends_on:
      - processing
  processing:
    build: ./processing/.
    ports:
     - "4568:4568"
    volumes:
      - $SURVEY_DATA_VOLUME:/opt/data
  divolte:
    build: ./divolte/
    ports:
      - "8290:8290"
    volumes:
      - "./divolte/divolte_clicklogs/inflight:/mnt/divolte_clicklogs/inflight"
      - "./divolte/divolte_clicklogs/published:/mnt/divolte_clicklogs/published"
volumes:
  redis-data: {}