version: '2'
services:
  nginx:
    restart: always
    build: ./survey/
    ports:
      - "8080:80"
    volumes:
      - /www/public
      - "./survey/app:/src/app"
    depends_on:
      - processing
  processing:
    build: ./processing/.
    ports:
     - "4568:4568"
    #links:
    # - redis
    # - db
    #depends_on:
    #  - redis
    #  - db
    volumes:
      - $SURVEY_DATA_VOLUME:/opt/data
  #redis:
  #  image: redis
  #  ports:
  #   - "6379:6379"
  #  volumes:
  #    - redis-data:/var/lib/redis
  #db:
  #  image: mongo
  #  ports:
  #    - "27017:27017"
  #    image: mkieboom/divolte-collector-docker
  divolte:
    build: ./divolte/
    ports:
      - "8290:8290"
    volumes:
      - "./divolte/divolte_clicklogs/inflight:/mnt/divolte_clicklogs/inflight"
      - "./divolte/divolte_clicklogs/published:/mnt/divolte_clicklogs/published"
volumes:
  redis-data: {}